spring:
  app:
    name: "${dev.spring.app.name}"
    env: "${dev.spring.app.env}"
    port: "${dev.spring.app.port}"

  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/ant_training_db"
    database: "${dev.spring.mysql.database}"
    root_password: "${dev.spring.mysql.root_password}"
    username: "${dev.spring.mysql.username}"
    password: "${dev.spring.mysql.password}"
    port: "${dev.spring.mysql.port}"



API:
  kiwoom:
    host: "${kiwoom.host}"
    oauth: "${kiwoom.oauth_endpoint}"
    search: "${kiwoom.search_endpoint}"
    app_key: "${kiwoom.kiwoom_app_key}"
    secret_key: "${kiwoom.kiwoom_secret_key}"
  discord:
    webhook_url: "${discord.webhook_url}"



